name: Azure Machine Learning CI/CD pipeline

on:
  push:
    branches:
      - main

jobs:
  experiment:
    runs-on: ubuntu-latest
    environment:
      name: development

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      # Setup and run your experiment job here
      - name: Run experiment job
        run: az ml job create --file src/job.yml --resource-group final-tutorial --workspace-name final-tutorial-mlw --stream

  production:
    needs: experiment
    runs-on: ubuntu-latest
    environment:
      name: production
      # url: ${{ secrets.PRODUCTION_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      # Setup and run your production job here
      - name: Run production job
        run: az ml job create --file src/job2.yml --resource-group final-tutorial --workspace-name final-tutorial-mlw 
