name: Deploy ML model to endpoint

on:
  workflow_dispatch:

jobs:
  deploy_model:
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Install az ml extension
        run: az extension add -n ml -y

      - name: Deploy model to endpoint
        run: |
          az ml online-endpoint create --name tutorial-endpoint -f src/endpoints.yml --resource-group final-tutorial --workspace-name final-tutorial-mlw
          az ml online-deployment create --name tutorial-deployment --endpoint tutorial-endpoint -f src/deployment.yml --all-traffic 