name: Deploy ML model to endpoint

on:
  workflow_dispatch:

jobs:
  deploy_model:
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Install az ml extension
        run: az extension add -n ml -y

      - name: Deploy model to endpoint
        run: |
          VERSION=$(az ml model show --name final-tutorial-model --workspace-name final-tutorial-mlw --query 'latest.version' -o tsv)
          az ml endpoint create --name final-tutorial-endpoint --type aks --model final-tutorial-model:$VERSION --workspace-name final-tutorial-mlw --resource-group final-tutorial
